config/routes.rb
Lagdown::Application.routes.draw do
  constraints subdomain: false do
    root 'home#index'
    devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}
    get 'select2/tags', format: :json
    get 'select2/results', format: :json
    post 'preview' => 'posts#preview'
    namespace :settings do
      resources :blogs do
        resources :posts, only: %i[new create edit update destroy]
      end
      resource :user, only: %i[edit update]
      resources :categories
    end

    # 使用者個人頁(user)
    get 'users/about' => 'home#about', :as => :about
  end

  constraints(Subdomain) do
    root 'posts#index', as: :blog_root
    resources :posts, only: %i[index show]
    
    # RSS訂閱
    get 'rss' => 'posts#rss'
    # 使用者個人頁
    get 'about' => 'home#about', :as => :profile
  end 

  namespace :admin do
    root 'home#index'
    devise_for :administrators, class_name: Admin::Administrator, singular: :administrator
    resources :administrators
    resources :users
    resources :posts
    resources :blogs
  end
end

app/models/admin/administrator.rb
# == Schema Information
#
# Table name: administrators
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class Admin::Administrator < ActiveRecord::Base
  devise :database_authenticatable, :timeoutable, :rememberable, :trackable, :validatable
end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < ApplicationController
  include AdminConcern
  before_action :set_admin_administrator, only: [:show, :edit, :update, :destroy]
  authorize_resource instance_name: :admin_administrator

  # GET /admin/administrators
  # GET /admin/administrators.json
  def index
    @admin_administrators = Admin::Administrator.page(params[:page])
  end

  # GET /admin/administrators/1
  # GET /admin/administrators/1.json
  def show
  end

  # GET /admin/administrators/new
  def new
    @admin_administrator = Admin::Administrator.new
  end

  # GET /admin/administrators/1/edit
  def edit
  end

  # POST /admin/administrators
  # POST /admin/administrators.json
  def create
    @admin_administrator = Admin::Administrator.new(admin_administrator_params)

    respond_to do |format|
      if @admin_administrator.save
        format.html { redirect_to @admin_administrator, notice: t('crud.created_successfully!', name: Admin::Administrator.model_name.human) }
        format.json { render action: 'show', status: :created, location: @admin_administrator }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/administrators/1
  # PATCH/PUT /admin/administrators/1.json
  def update
    respond_to do |format|
      if @admin_administrator.update(admin_administrator_params)
        format.html { redirect_to @admin_administrator, notice: t('crud.updated_successfully!', name: Admin::Administrator.model_name.human) }
        format.json { render action: 'show', status: :ok, location: @admin_administrator }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/administrators/1
  # DELETE /admin/administrators/1.json
  def destroy
    @admin_administrator.destroy
    respond_to do |format|
      format.html { redirect_to admin_administrators_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_administrator
      @admin_administrator = Admin::Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_administrator_params
      params.require(:admin_administrator).permit(:email, :password)
    end
end

app/views/admin/administrators/_form.html.erb
<%= simple_form_for(@admin_administrator, bootstrap_form_options(form_class: 'form-horizontal')) do |f| %>
  <%= f.error_notification class: 'alert alert-danger' %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/admin/administrators/edit.html.erb
<div class="page-header">
  <h1><%= t('crud.edit!', resource: Admin::Administrator.model_name.human).titleize %></h1>
</div>

<%= render 'form' %>

<%= link_to t('crud.show'), @admin_administrator %> |
<%= link_to t('action.back'), admin_administrators_path %>

app/views/admin/administrators/index.html.erb
<div class="page-header">
  <%= link_to_if can?(:create, Admin::Administrator), t('crud.new!', resource: Admin::Administrator.model_name.human), new_admin_administrator_path, class: 'btn btn-primary btn-lg pull-right' %>
  <h1><%= Admin::Administrator.model_name.human %></h1>
</div>

<%= paginate @admin_administrators %>

<%= table_for @admin_administrators, :email, class: 'table table-striped' %>

<%= paginate @admin_administrators %>

app/views/admin/administrators/new.html.erb
<div class="page-header">
  <h1><%= t('crud.new!', resource: Admin::Administrator.model_name.human) %></h1>
</div>

<%= render 'form' %>

<%= link_to t('action.back'), admin_administrators_path %>

app/views/admin/administrators/show.html.erb
<%= dl_for @admin_administrator, :email %>
<%= link_to_if can?(:edit, @admin_administrator), t('crud.edit'), edit_admin_administrator_path(@admin_administrator) %> |
<%= link_to t('action.back'), admin_administrators_path %>