config/routes.rb
Lagdown::Application.routes.draw do
  constraints subdomain: false do
    root 'home#index'
    devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}
    get 'select2/tags', format: :json
    get 'select2/results', format: :json
    post 'preview' => 'posts#preview'
    namespace :settings do
      resources :blogs do
        resources :posts, only: %i[new create edit update destroy]
      end
      resource :user, only: %i[edit update]
      resources :categories
    end

    # 使用者個人頁(user)
    get 'users/about' => 'home#about', :as => :about
  end

  constraints(Subdomain) do
    root 'posts#index', as: :blog_root
    resources :posts, only: %i[index show]
    
    # RSS訂閱
    get 'rss' => 'posts#rss'
    # 使用者個人頁
    get 'about' => 'home#about', :as => :profile
  end 

  namespace :admin do
    root 'home#index'
    devise_for :administrators, class_name: Admin::Administrator, singular: :administrator
    resources :administrators
    resources :users
    resources :posts
    resources :blogs
  end
end

app/views/share/admin/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><%= t('site_name') %> Admin</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <% [Admin::Administrator, Admin::User, Admin::Blog, Admin::Post].each do |model|  %>
        <%= nav_li_for model %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Back to the front', root_path %></li>
      <% if administrator_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_administrator.email %><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Sign out', destroy_administrator_session_path, method: :delete %></li>
        </ul>
      </li>
      <% else %>
        <li><%= link_to 'Sign in', new_administrator_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>