config/routes.rb
Lagdown::Application.routes.draw do
  constraints subdomain: false do
    root 'home#index'
    devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}
    get 'select2/tags', format: :json
    get 'select2/results', format: :json
    post 'preview' => 'posts#preview'
    namespace :settings do
      resources :blogs do
        resources :posts, only: %i[new create edit update destroy]
      end
      resource :user, only: %i[edit update]
      resources :categories
    end

    # 使用者個人頁(user)
    get 'users/about' => 'home#about', :as => :about
  end

  constraints(Subdomain) do
    root 'posts#index', as: :blog_root
    resources :posts, only: %i[index show]
    
    # RSS訂閱
    get 'rss' => 'posts#rss'
    # 使用者個人頁
    get 'about' => 'home#about', :as => :profile
  end 

  namespace :admin do
    root 'home#index'
    devise_for :administrators, class_name: Admin::Administrator, singular: :administrator
    resources :administrators
    resources :users
    resources :posts
    resources :blogs
  end
end

app/models/admin/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :integer          not null, primary key
#  subdomain  :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  name       :string(255)      not null
#

class Admin::Blog < Blog
  # scope macros

  # Concerns macros

  # Constants
  
  # Attributes related macros

  # association macros
  belongs_to :user, class_name: Admin::User
  has_many :posts, class_name: Admin::Post, dependent: :destroy

  # validation macros

  # callbacks

  # other

  protected
  # callback methods
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :integer          not null, primary key
#  subdomain  :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  name       :string(255)      not null
#

class Blog < ActiveRecord::Base
  # scope macros

  # Concerns macros
  include Select2Concern

  # Constants
  SUBDOMAIN_BLACK_LIST = %w[www admin api xdite]
  
  # Attributes related macros
  select2_white_list :subdomain

  # association macros
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :categories
  # validation macros
  validates :user, :name, :subdomain, presence: true
  validates :subdomain, uniqueness: true, exclusion: { in: SUBDOMAIN_BLACK_LIST }
  validate :limit_blog_number, on: :create

  # callbacks
  before_save :downcase
  # other

  protected
  # callback methods
  def limit_blog_number
    errors.add(:base, :too_many_blogs) if user.blogs.size > 3
  end

  def downcase
    self.subdomain = self.subdomain.downcase
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/settings/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :integer          not null, primary key
#  subdomain  :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  name       :string(255)      not null
#

class Settings::Blog < Blog
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  include AdminConcern
  before_action :set_admin_blog, only: [:show, :edit, :update, :destroy]
  authorize_resource instance_name: :admin_blog

  # GET /admin/blogs
  # GET /admin/blogs.json
  def index
    @admin_blogs = Admin::Blog.page(params[:page])
  end

  # GET /admin/blogs/1
  # GET /admin/blogs/1.json
  def show
  end

  # GET /admin/blogs/new
  def new
    @admin_blog = Admin::Blog.new
  end

  # GET /admin/blogs/1/edit
  def edit
  end

  # POST /admin/blogs
  # POST /admin/blogs.json
  def create
    @admin_blog = Admin::Blog.new(admin_blog_params)

    respond_to do |format|
      if @admin_blog.save
        format.html { redirect_to @admin_blog, notice: t('crud.created_successfully!', name: Admin::Blog.model_name.human) }
        format.json { render action: 'show', status: :created, location: @admin_blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/blogs/1
  # PATCH/PUT /admin/blogs/1.json
  def update
    respond_to do |format|
      if @admin_blog.update(admin_blog_params)
        format.html { redirect_to @admin_blog, notice: t('crud.updated_successfully!', name: Admin::Blog.model_name.human) }
        format.json { render action: 'show', status: :ok, location: @admin_blog }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/blogs/1
  # DELETE /admin/blogs/1.json
  def destroy
    @admin_blog.destroy
    respond_to do |format|
      format.html { redirect_to admin_blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_blog
      @admin_blog = Admin::Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_blog_params
      params.require(:admin_blog).permit(:name, :subdomain, :user_id)
    end
end

app/controllers/settings/blogs_controller.rb
class Settings::BlogsController < ApplicationController
  include SettingsConcern
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  authorize_resource

  def index
    @blogs = Settings::Blog.where(user_id: current_user.id).page(params[:page])
  end

  def show
    if params[:category_id] == "null"
      @posts = @blog.posts.order(created_at: :desc).where(category_id: nil).page(params[:page]).per(10)      
    elsif params[:category_id] 
      @posts = @blog.posts.order(created_at: :desc).where(category_id: params[:category_id]).page(params[:page]).per(10)
    else
      @posts = @blog.posts.order(created_at: :desc).page(params[:page]).per(10)
    end
    @cat_nil = @blog.posts.where(category_id: nil).count
  end

  def new
    @blog = Settings::Blog.new
  end

  def create
    @blog = Settings::Blog.new(blog_params)
    @blog.user = current_user

    if @blog.save
      redirect_to @blog, notice: t('crud.created_successfully!', name: Settings::Blog.model_name.human)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @blog.update blog_params
      redirect_to @blog, notice: t('crud.updated_successfully!', name: Settings::Blog.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to Settings::Blog
  end

  private
  def set_blog
    # 有漏洞，可藉由網址參數直接訪問網頁
    # @blog = Settings::Blog.find(params[:id])

    # 藉由判斷 user_id = current_user.id 來斷定使用者，是否有更好的解法？
    user_id = Settings::Blog.find(params[:id]).user_id
    @blog = Settings::Blog.find(params[:id]) if user_id == current_user.id
  end

  def blog_params
    params.require(:settings_blog).permit(:name, :subdomain)
  end

end

app/controllers/settings/categories_controller.rb
class Settings::CategoriesController < ApplicationController
  include SettingsConcern
  before_action :set_cat , only: %i[destroy update edit show]
  before_action :set_blogs , only: %i[index create edit show]
  before_action :set_index , only: %i[index create]

  def index
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

      if @category.save
        # redirect_to 'index'
        redirect_to settings_categories_path
      else
        render :index
      end
  end

  def destroy
    @cat.posts.each do |p|
        p.update_columns(:category_id => nil)
    end if @cat.destroy

    redirect_to settings_categories_path
  end

  def edit
    @category = @cat
    @detail = {
      :title => t('category.edit')+ " => "+ @cat.name,
      :gly_type =>'glyphicon-edit',
      :action =>'update'}
  end

  def update
    @cat.update category_params
    redirect_to settings_categories_path
  end

  def show
    if @cat.update params.permit(:blog_id)
      @cat.posts.each do |p|
        p.update_columns(:category_id => nil)
      end
      redirect_to settings_categories_path
    else
    render 'index'
    end
  end

private
  def category_params
    params.require(:category).permit(:name,:blog_id)
  end

  def blog_params
    params.require(:blog).permit(:blog_id)
  end

  def set_blogs
    @blogs = current_user.blogs
  end

  def set_cat
    blog_id =  Category.find(params[:id]).blog_id
    @cat = Category.find(params[:id]) if check_blog blog_id
  end

  # check the pramas if id really is current_user's
  def check_blog id
    blogs_id = current_user.blogs.map {|blog| blog.id}
    blogs_id.include?(id)
  end

  def set_index
    @list = []
    @blogs.each do |b| 
      @list.push({:name => b.name,:id => b.id})
    end
    # 尚未分類's categroy_list
    # @list.push({:name =>'尚未分類',:id => nil})

    @detail = {
    title: t('category.add'),
    gly_type: 'glyphicon-plus-sign',
    action: 'create'}
  end
end

app/controllers/settings/posts_controller.rb
class Settings::PostsController < ApplicationController
  include SettingsConcern
  before_action :set_blog
  before_action :set_post, only: %i[show edit update destroy]
  authorize_resource

  def index
    @posts = @blog.posts.page(params[:page])
  end

  def show
  end

  def new
    @post = @blog.posts.new
  end

  def create
    @post = @blog.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post, subdomain: @blog.subdomain), notice: t('crud.created_successfully!', name: Post.model_name.human)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to post_url(@post, subdomain: @blog.subdomain), notice: t('crud.updated_successfully!', name: Post.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to @blog
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end

  def set_blog
    user_id = Settings::Blog.find(params[:blog_id]).user_id
    @blog = Settings::Blog.find(params[:blog_id]) if check_user user_id
  end

  def set_post
    blog_id = Post.find(params[:id]).blog_id 
    @post = Post.find(params[:id]) if check_blog blog_id
  end

  # check the pramas if id really is current_user's
  def check_blog id
    blogs_id = current_user.blogs.map {|blog| blog.id}
    blogs_id.include?(id)
  end
  def check_user id
    user_id = current_user.id
    user_id == id
  end

end

app/controllers/settings/users_controller.rb
class Settings::UsersController < ApplicationController
  include SettingsConcern
  before_action :set_user, only: %i[edit update]
  authorize_resource

  def edit
  end

  def update
    if @user.update user_params
      redirect_to edit_settings_user_path, notice: t('crud.updated_successfully!', name: '')
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :about, :homepage, :avatar)
  end

  def set_user
    @user = current_user
  end
end

app/views/settings/blogs/_form.html.erb
<%= simple_form_for(@blog, **bootstrap_form_options(form_class: 'form-horizontal')) do |f| %>
  <%= f.error_notification class: 'alert alert-danger' %>
  <% if base_errors = @blog.errors[:base].presence %>
    <div class="alert alert-danger">
      <% base_errors.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :subdomain %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/settings/blogs/edit.html.erb
<h4>
<%= gly_icon t('action.back'),Settings::Blog,'backward','btn-default'%>
</h4>
<h1><%= t('crud.edit!', resource: Settings::Blog.model_name.human).titleize %></h1>

<%= render 'form' %>

app/views/settings/blogs/index.html.erb
<div class="page-header">
  <%= link_to t('crud.new!', resource: Settings::Blog.model_name.human), new_settings_blog_path, class: 'btn btn-primary btn-lg pull-right' %>
  <h1><%= Settings::Blog.model_name.human %></h1>
</div>


<%= paginate @blogs %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Settings::Blog.human_attribute_name(:name) %></th>
      <th><%= Settings::Blog.human_attribute_name(:subdomain) %></th>
      <th><%= t('.blog_url') %></th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to blog.name, blog %></td>
        <td><%= blog.subdomain %></td>
        <td><%= link_to root_url(subdomain: blog.subdomain), root_url(subdomain: blog.subdomain) %></td>
        <td><%= link_to t('crud.edit'), edit_settings_blog_path(blog) %></td>
        <td><%= link_to t('crud.delete'), settings_blog_path(blog), method: :delete, data: {confirm: t('message.are_you_sure')} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @blogs %>

app/views/settings/blogs/new.html.erb
<h1><%= t('crud.new!', resource: Settings::Blog.model_name.human).titleize %></h1>

<%= render 'form' %>

<%= link_to t('action.back'), settings_blogs_path %>

app/views/settings/blogs/show.html.erb
<h4>
<%= gly_icon t('action.back'),Settings::Blog,'backward','btn-default'%>
<%= gly_icon t('crud.edit'),[:edit,@blog],'cog','btn btn-primary'%>
</h4>
<!--Blog detail-->
<%= dl_for @blog, :name %>
<%= t('subdomain')%><br>
<%= link_to root_url(host: Settings.host, subdomain: @blog.subdomain).to_s,root_url(host: Settings.host, subdomain: @blog.subdomain)%>


<hr><!--Category list-->
<!--cate_all-->
<% str_all = t('category.all')+" ( " + @blog.posts.count.to_s + " )"  %>
<%= button_li str_all,settings_blog_path%>
<!--cate_each-->
<% @blog.categories.each do |c|%>
<% cc = c.name.to_s + " ( "+ c.posts.count.to_s + " )" %>
<%= button_li cc,settings_blog_path(@blog,category_id: c.id)%>
<%end%>
<!--cate_nil-->
<% str_nil = t('category.nil')+" ( " + @cat_nil.to_s + " )" if @cat_nil > 0 %>
<%= button_li str_nil,settings_blog_path(@blog,category_id: "null") if @cat_nil > 0 %>

<!--Posts list-->
<p><%= paginate @posts %></p>
<table class="table table-hover">
  <thead><!--title and new post-->
    <tr>
      <td style="width:80%"><h1><%= Post.human_attribute_name(:title) %></h1></td>
      <td style="width:20%"><%= gly_icon t('crud.new!',resource: Post.model_name.human),new_settings_blog_post_path(@blog),"pencil","btn-lg btn-success"%></td>
    </tr>
  </thead>

  <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td style="width:80%" class="list-group"><!--all post-->
            <div >
              <%= link_to post_url(post,subdomain: @blog.subdomain),class: "list-group-item" do %>
                <h4 class="list-group-item-heading"><%= post.title%></h4>
                <span class="glyphicon glyphicon-search">【<%= Category.where(id:post.category_id).pluck(:name).first%>】</span>
                  【<%= t('post.view_count')%> : <%= post.view_count%>】
                  【<%= t('crud.updated')%> : <%= post.updated_at%>】
                  【<%= t('crud.created')%> : <%= post.created_at%>】            
                <hr>
                <p class="list-group-item-text"><%= post.content.slice(0..150)%> ......</p>
              <%end%>
            </div> 
          </td>
          <td style="width:20%"><!--action button: edit / delete-->
            <%= gly_icon t('crud.edit'),edit_settings_blog_post_path(@blog,post),"edit","btn-primary btn-lg"%>
            <%= gly_icon '',[@blog,post],"trash","btn-danger btn-lg",method: :delete,data: {confirm: t('message.are_you_sure')}%>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>
<%= paginate @posts %>