config/routes.rb
Lagdown::Application.routes.draw do
  constraints subdomain: false do
    root 'home#index'
    devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}
    get 'select2/tags', format: :json
    get 'select2/results', format: :json
    post 'preview' => 'posts#preview'
    namespace :settings do
      resources :blogs do
        resources :posts, only: %i[new create edit update destroy]
      end
      resource :user, only: %i[edit update]
      resources :categories
    end

    # 使用者個人頁(user)
    get 'users/about' => 'home#about', :as => :about
  end

  constraints(Subdomain) do
    root 'posts#index', as: :blog_root
    resources :posts, only: %i[index show]
    
    # RSS訂閱
    get 'rss' => 'posts#rss'
    # 使用者個人頁
    get 'about' => 'home#about', :as => :profile
  end 

  namespace :admin do
    root 'home#index'
    devise_for :administrators, class_name: Admin::Administrator, singular: :administrator
    resources :administrators
    resources :users
    resources :posts
    resources :blogs
  end
end

app/models/admin/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  content    :text             not null
#  blog_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Admin::Post < Post
  # scope macros

  # Concerns macros

  # Constants
  
  # Attributes related macros

  # association macros
  belongs_to :blog, class_name: Admin::Blog

  # validation macros

  # callbacks

  # other

  protected
  # callback methods
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  content    :text             not null
#  blog_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  view_count :integer          default:0

class Post < ActiveRecord::Base
  # scope macros
  
  # Concerns macros

  # Constants
  
  # Attributes related macros

  # association macros
  belongs_to :blog

  # validation macros
  validates :title, :content, :blog, presence: true

  # callbacks

  # other

  protected
  # callback methods
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  include AdminConcern
  before_action :set_admin_post, only: [:show, :edit, :update, :destroy]
  authorize_resource instance_name: :admin_post

  # GET /admin/posts
  # GET /admin/posts.json
  def index
    @admin_posts = Admin::Post.page(params[:page])
  end

  # GET /admin/posts/1
  # GET /admin/posts/1.json
  def show
  end

  # GET /admin/posts/new
  def new
    @admin_post = Admin::Post.new
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  # POST /admin/posts.json
  def create
    @admin_post = Admin::Post.new(admin_post_params)

    respond_to do |format|
      if @admin_post.save
        format.html { redirect_to @admin_post, notice: t('crud.created_successfully!', name: Admin::Post.model_name.human) }
        format.json { render action: 'show', status: :created, location: @admin_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/posts/1
  # PATCH/PUT /admin/posts/1.json
  def update
    respond_to do |format|
      if @admin_post.update(admin_post_params)
        format.html { redirect_to @admin_post, notice: t('crud.updated_successfully!', name: Admin::Post.model_name.human) }
        format.json { render action: 'show', status: :ok, location: @admin_post }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.json
  def destroy
    @admin_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_post
      @admin_post = Admin::Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_post_params
      params.require(:admin_post).permit(:title, :content, :blog_id)
    end
end

app/controllers/posts_controller.rb
require "rss"

class PostsController < ApplicationController
  before_action :set_blog, only: %i[index show rss]
  before_action :set_post, only: %i[show]
  before_action :set_user, only: %i[rss]
  before_action :set_view_count,only: %i[show]
  authorize_resource except: [:preview,:rss]
  layout 'blog'

  def index
    @posts = @blog.posts.order(created_at: :desc).page(params[:page])
  end

  def show
    description = LagdownRenderer.render(@post.content)[/<p>([^<].*)<\/p>/, 1]
    @title =  "#{@post.title} - #{@blog.name}"
    @meta_hash = {
      author: @blog.user.try(:nickname),
      description: description,
      generator: :lagdown
    }
    @og_hash = {
      title: @title,
      type:  :website,
      url: post_url(@post),
      description: description
    }
  end

  def preview
    render text: LagdownRenderer.render(params[:text].to_s)
  end

  def rss
    @rss = RSS::Maker.make("2.0") do |maker|
      maker.channel.language = "en"
      maker.channel.author = @blog.subdomain
      maker.channel.updated = Time.now.to_s
      maker.channel.link = root_url(host: Settings.host, subdomain: @blog.subdomain)
      maker.channel.title = @user.nickname + "'s Lagdown Blog"
      maker.channel.description = "Lagdown - The Markdown Blogging System"
      maker.channel.copyright = "Copyright © 2014 Lagdown-Blogging System. All rights reserved"

      @blog.posts.each do |p|
        maker.items.new_item do |item|
          item.link = post_url(p, subdomain: @blog.subdomain)
          item.author = @blog.subdomain
          item.title = p.title
          item.description = p.content.slice(1..100) + " ......"
          item.updated = p.updated_at.to_s
        end
      end
    end
    # respond_to do |format|
    #   format.xml { render :xml => @rss.to_xml }
    # end
    render :xml => @rss.to_xml
  end

private
  def set_blog
    @blog = Blog.find_by_subdomain! request.subdomain
  end

  def set_post
    @post = @blog.posts.find(params[:id])
  end

  def set_user
    @user = Blog.find_by_subdomain!(request.subdomain).user
  end

  def set_view_count
    # clear the setting_time ip_session
    Session.sweep(10.second)

    ip_nil = Session.where(ip: request.remote_ip).first.nil?

    if ip_nil
      # add count
      count = @post.view_count
      count += 1
      @post.update_columns(view_count: count)
      # add ip session
      Session.create(ip: request.remote_ip)
    else
    end
  end

end

app/controllers/settings/posts_controller.rb
class Settings::PostsController < ApplicationController
  include SettingsConcern
  before_action :set_blog
  before_action :set_post, only: %i[show edit update destroy]
  authorize_resource

  def index
    @posts = @blog.posts.page(params[:page])
  end

  def show
  end

  def new
    @post = @blog.posts.new
  end

  def create
    @post = @blog.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post, subdomain: @blog.subdomain), notice: t('crud.created_successfully!', name: Post.model_name.human)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to post_url(@post, subdomain: @blog.subdomain), notice: t('crud.updated_successfully!', name: Post.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to @blog
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end

  def set_blog
    user_id = Settings::Blog.find(params[:blog_id]).user_id
    @blog = Settings::Blog.find(params[:blog_id]) if check_user user_id
  end

  def set_post
    blog_id = Post.find(params[:id]).blog_id 
    @post = Post.find(params[:id]) if check_blog blog_id
  end

  # check the pramas if id really is current_user's
  def check_blog id
    blogs_id = current_user.blogs.map {|blog| blog.id}
    blogs_id.include?(id)
  end
  def check_user id
    user_id = current_user.id
    user_id == id
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-sm-10">
      <h1>
        <%= @blog.name %>
        <%= link_to (image_tag "rss.png",size:"50x20",alt: "rss.tag"),rss_path%>
      </h1>    

    </div><!--col-sm-->
    <div class="col-sm-2">
      <div>
        <%= link_to t('blog.manage'),settings_blog_url(@blog),class: "btn btn-block btn-primary"%>
        <%= link_to t('blog.about'),profile_path,class: "btn btn-block btn-warning"%>
      </div>
    </div><!--col-sm-->
  </div><!--row-->

</div><!--page header-->

<div class="row">
  <div class="col-sm-9">
    <% @posts.each do |post| %>
      <div class="page-header">
        <blockquote style="border-color: #FFB840">
          <h3><%= link_to post.title, post_path(post) %></h3>
          <footer>
            <span class="glyphicon glyphicon-search">【<%= Category.where(id:post.category_id).pluck(:name).first%>】【<%= t('post.view_count')%>：<%= post.view_count%>】
            </span>
            <p>
            【<%= t('crud.updated')%> : <%= post.updated_at%>】
            【<%= t('crud.created')%> : <%= post.created_at%>】        
            </p>    
          </footer>
        </blockquote>
      </div>
      <div class="highlight">
        <%= sanitize LagdownRenderer.render(post.content) %>
      </div>
    <% end %>
  </div><!--col-sm-->    
<div><!--row-->

<div><!--row-->

<%= paginate @posts %>

<%= mathjax_script_tag %>

app/views/posts/show.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-sm-10">
      <h1><%= @post.title %></h1>
    </div><!--col-sm-->
    <div class="col-sm-2">
      <div>
        <%= link_to t('blog.manage'),settings_blog_url(@blog),class: "btn btn-block btn-primary"%>
        <%= link_to t('blog.about'),profile_path,class: "btn btn-block btn-warning"%>
      </div>
    </div><!--col-sm-->
  </div><!--row-->

<hr>
<div class="highlight">
  <%= sanitize LagdownRenderer.render(@post.content) %>
</div>
<br><br><br><br>
<p class="text-right"><em><strong><%= t('post.view_count')%>：<%= @post.view_count%></strong></em></p>
<%= gly_icon t('action.back'), root_path,'backward','btn-default' %>
<%= gly_icon t('action.edit'),edit_settings_blog_post_url(@blog, @post),"edit","btn-primary" if can?(:edit, @post) %>

<%= mathjax_script_tag %>

<br><br><br><br>

<!--disqus comment-->
<div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'treekey999'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>